import SwiftUI
import ComposeApp

extension Book {
    var localizedName: String {
        let resourceKey: String
        switch self {
        case .genesis: resourceKey = "book_genesis"
        case .exodus: resourceKey = "book_exodus"
        case .leviticus: resourceKey = "book_leviticus"
        case .numbers: resourceKey = "book_numbers"
        case .deuteronomy: resourceKey = "book_deuteronomy"
        case .joshua: resourceKey = "book_joshua"
        case .judges: resourceKey = "book_judges"
        case .ruth: resourceKey = "book_ruth"
        case .samuel1: resourceKey = "book_1samuel"
        case .samuel2: resourceKey = "book_2samuel"
        case .kings1: resourceKey = "book_1kings"
        case .kings2: resourceKey = "book_2kings"
        case .chronicles1: resourceKey = "book_1chronicles"
        case .chronicles2: resourceKey = "book_2chronicles"
        case .ezra: resourceKey = "book_ezra"
        case .nehemiah: resourceKey = "book_nehemiah"
        case .esther: resourceKey = "book_esther"
        case .job: resourceKey = "book_job"
        case .psalms: resourceKey = "book_psalms"
        case .proverbs: resourceKey = "book_proverbs"
        case .ecclesiastes: resourceKey = "book_ecclesiastes"
        case .songOfSolomon: resourceKey = "book_song_of_solomon"
        case .isaiah: resourceKey = "book_isaiah"
        case .jeremiah: resourceKey = "book_jeremiah"
        case .lamentations: resourceKey = "book_lamentations"
        case .ezekiel: resourceKey = "book_ezekiel"
        case .daniel: resourceKey = "book_daniel"
        case .hosea: resourceKey = "book_hosea"
        case .joel: resourceKey = "book_joel"
        case .amos: resourceKey = "book_amos"
        case .obadiah: resourceKey = "book_obadiah"
        case .jonah: resourceKey = "book_jonah"
        case .micah: resourceKey = "book_micah"
        case .nahum: resourceKey = "book_nahum"
        case .habakkuk: resourceKey = "book_habakkuk"
        case .zephaniah: resourceKey = "book_zephaniah"
        case .haggai: resourceKey = "book_haggai"
        case .zechariah: resourceKey = "book_zechariah"
        case .malachi: resourceKey = "book_malachi"
        case .matthew: resourceKey = "book_matthew"
        case .mark: resourceKey = "book_mark"
        case .luke: resourceKey = "book_luke"
        case .john: resourceKey = "book_john"
        case .acts: resourceKey = "book_acts"
        case .romans: resourceKey = "book_romans"
        case .corinthians1: resourceKey = "book_1corinthians"
        case .corinthians2: resourceKey = "book_2corinthians"
        case .galatians: resourceKey = "book_galatians"
        case .ephesians: resourceKey = "book_ephesians"
        case .philippians: resourceKey = "book_philippians"
        case .colossians: resourceKey = "book_colossians"
        case .thessalonians1: resourceKey = "book_1thessalonians"
        case .thessalonians2: resourceKey = "book_2thessalonians"
        case .timothy1: resourceKey = "book_1timothy"
        case .timothy2: resourceKey = "book_2timothy"
        case .titus: resourceKey = "book_titus"
        case .philemon: resourceKey = "book_philemon"
        case .hebrews: resourceKey = "book_hebrews"
        case .james: resourceKey = "book_james"
        case .peter1: resourceKey = "book_1peter"
        case .peter2: resourceKey = "book_2peter"
        case .john1: resourceKey = "book_1john"
        case .john2: resourceKey = "book_2john"
        case .john3: resourceKey = "book_3john"
        case .jude: resourceKey = "book_jude"
        case .revelation: resourceKey = "book_revelation"
        @unknown default:
            return self.name
        }
        return NSLocalizedString(resourceKey, comment: "")
    }
}
